routes/web.php
<?php

use App\Http\Controllers\AcademiesController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ContestantController;
use App\Http\Controllers\Admin\EventsController;
use App\Http\Controllers\Admin\LandingPageSettingController;
use App\Http\Controllers\Admin\MentorController;
use App\Http\Controllers\Admin\SchoolController;
use App\Http\Controllers\Admin\TimeScheduleController;
use App\Http\Controllers\Admin\TechnicalMeetingController;
use App\Http\Controllers\Admin\UniversityController;
use App\Http\Controllers\Admin\UserListController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\DownloadController;
use App\Http\Controllers\EventRegisterController;
use App\Http\Controllers\LandingController;
use App\Http\Controllers\User\ValidationController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ViewMentorController;
use App\Http\Controllers\ViewTimeScheduleController;
use App\Http\Controllers\ViewUserListController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ResetPasswordController;
use PhpParser\Builder\Class_;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
//
*/


Route::get('/', [LandingController::class,'index']);

Route::get('detail-berita/{id}', [LandingController::class,'detail']);

Route::get('lihat-pdf/{id}', [LandingController::class,'viewPDF']);

Route::get('/blog', function () {
    return view('user.setting.edit');
});

Route::resource('pendamping', ViewMentorController::class);

Route::get('/time', [ViewTimeScheduleController::class, 'indexTimeSchedule']);


// Route::get('/time', function () {
//     return view('user.time');
// });

// Route::get('/pendamping', function () {
//     return view('user.pendamping');
// });

Route::get('/detaillomba', function () {
    return view('competition-detail');
});


Route::prefix('/event')->group(function(){

     // AcademyRegister
        Route::get('school',function(){
            return view('register.academy.school');
        })->name('academies.scholl');

        // UniversityRegister
        Route::get('university',function(){
            return view('register.academy.university');
        })->name('academies.university');


    Route::get('/{id}',[EventController::class,'index'])->name('event.detail');
    Route::get('/{id}/form',[EventController::class,'form'])->name('event.form');
    Route::resource('academies',AcademiesController::class);
    route::resource('register',EventRegisterController::class);

});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// User

route::get('/download/{id}',[DownloadController::class,'downloadbooklet'])->name('downloadbooklet');

route::group(['middleware' => ['role:Users','auth'],'prefix' => 'users'],function(){
    route::resource('dashboard',UserController::class);
    route::get('/list-peserta',[ViewUserListController::class,'index'])->name('listpeserta.index');
    route::get('/validation',[ValidationController::class,'index'])->name('user.validation');
    route::post('/validation',[ValidationController::class,'updateValidation'])->name('user.validate');
});

// Admin
route::group(['middleware' => ['role:Administrator'],'prefix' => 'admin',],function(){
    Route::get('/', [DashboardController::class,'index'])->name('admin.dashboard');

    route::get('download/{id}/{validation_no}',[DownloadController::class,'download'])->name('download');


    route::resource('member',AdminController::class);
    route::resource('mentors',MentorController::class);
    route::resource('schedules',TimeScheduleController::class);
    route::resource('events',EventsController::class);
    route::resource('blogs',BlogController::class);
    route::resource('tm',TechnicalMeetingController::class);
    route::resource('school',SchoolController::class);
    route::resource('university',UniversityController::class);

    Route::get('/cetak_pdf/{id}', [EventsController::class,'cetak_pdf'])->name('cetak_pdf');
    Route::get('/lihat_peserta/{id}', [EventsController::class,'lihat_peserta'])->name('lihat_peserta');
    route::get('/userlist/{id}',[UserListController::class,'index'])->name('userlist.index');
    // route::get('/userlist/{id}',[UserListController::class,'index2'])->name('userlist.index2');
    // Contestant
    route::resource('contestants',ContestantController::class);
    Route::get('/reset_password/{id}',[ResetPasswordController::class,'resetpsd'])->name('reset_password.resetpsd');

   // ACC
    Route::get('/acc/{id}',[ValidationController::class,'validateAcc'])->name('validation.acc');

    // Landing Page Setting
    Route::get('/landing',[LandingPageSettingController::class,'getLandingSet'])->name('landing.index');
    Route::post('/post',[LandingPageSettingController::class,'updateLandingSet'])->name('landing.update');

});

app/Models/Mentor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mentor extends Model
{
    use HasFactory;
    protected $fillable = [
        'academy_id',
        'event_id',
        'name',
        'phone',
        'identity_code'
    ];

    public function academy(){
        return $this->belongsTo(Academy::class,'academy_id');
    }

    public function events(){
        return $this->belongsTo(Event::class,'event_id');
    }

}

app/Http/Controllers/Admin/MentorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Academy;
use App\Models\Event;
use App\Models\Mentor;
use Illuminate\Http\Request;

class MentorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Mentor::paginate(10);
        return view('admin.mentor.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $academy = Academy::all();
        $event = Event::all();
        return view('admin.mentor.add')->with(compact('academy','event'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'academy_id'=> 'required',
            'event_id' => 'required',
            'name' => 'required',
            'phone' => 'required',
            'identity_code' => 'required|unique:mentors,identity_code'
        ],[
            // 'phone.unique' => "Data Sudah Ada !",
            'identity_code.unique' => "Data Sudah Ada !"
        ]);

        try {
            Mentor::create([
                'academy_id' => $request->academy_id,
                'event_id' => $request->event_id,
                'name' => $request->name,
                'phone' => $request->phone,
                'identity_code' => $request->identity_code
            ]);
            return redirect()->route('mentors.index')->with('success', 'Data Berhasil Ditambah');

        } catch (\Throwable $th) {
            return $th;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mentor = Mentor::find($id);
        $academy = Academy::all();
        $event = Event::all();
        return view('admin.mentor.edit')->with(compact('mentor','academy','event'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'academy_id'=> 'required',
            'event_id' => 'required',
            'name' => 'required',
            'phone' => 'required',
            'identity_code' => 'required'
        ]);

        try {
            Mentor::find($id)->update([
                'academy_id' => $request->academy_id,
                'event_id' => $request->event_id,
                'name' => $request->name,
                'phone' => $request->phone,
                'identity_code' => $request->identity_code
            ]);
            return redirect()->route('mentors.index')->with('success', 'Data Berhasil Diubah');

        } catch (\Throwable $th) {
            return $th;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            Mentor::find($id)->delete();
            return redirect()->route('mentors.index');
        } catch (\Throwable $th) {
            echo 'gagal';
        }
    }
}

app/Http/Controllers/User/ValidationController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Mail\VerificationEmail;
use App\Models\Event;
use App\Models\User;
use App\Models\UserDetail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;

class ValidationController extends Controller
{
    //

    public function index(){

        $path = Storage::disk('local')->get('public/landing_page_config.json');
        $data = json_decode($path,true);

        $url_document = $data['url_document'];

        if(Auth::user()->details->events->audience === "university"){
            return view('user.validation.university');
        }else{
            return view('user.validation.school')->with(compact('url_document'));
        }
    }

    public function updateValidation(Request $request){
        $request->validate([
            'validation_1' => 'image|mimes:jpeg,jpg,png|max:5000',
            'validation_2' => 'image|mimes:jpeg,jpg,png|max:5000',
            'validation_3' => 'image|mimes:jpeg,jpg,png|max:5000',
            'validation_4' => 'image|mimes:jpeg,jpg,png|max:5000',
            'validation_5' => 'image|mimes:jpeg,jpg,png|max:5000'
        ],[
            'validation_1.image' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_2.image' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_3.image' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_4.image' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_5.image' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_1.mimes' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_2.mimes' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_3.mimes' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_4.mimes' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_5.mimes' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_1.max' => "Format file maksimal 5 MB",
            'validation_2.max' => "Format file maksimal 5 MB",
            'validation_3.max' => "Format file maksimal 5 MB",
            'validation_4.max' => "Format file maksimal 5 MB",
            'validation_5.max' => "Format file maksimal 5 MB"
        ]);
        $user = Auth::user()->details;

        $event = Auth::user()->details->events;
        $event_name = $event->aliases.$event->year;

        $url = 'img/participant/'.$event_name.'/'. strtolower(str_replace(' ','_',Auth::user()->name));

        $validation_1 = $request->file('validation_1');
        $validation_1_name =  $user->identity_code . "-" . str_replace(' ','_',Auth::user()->name) . "-" . $user->events->aliases . $user->events->year. "." . $validation_1->getClientOriginalExtension();


        $validation_2 = $request->file('validation_2');
        $validation_2_name = $user->identity_code . "-" . str_replace(' ','_',Auth::user()->name) . "-" . $user->events->aliases . $user->events->year. "." . $validation_2->getClientOriginalExtension();

        $validation_3 = $request->file('validation_3');
        $validation_3_name = $user->identity_code . "-" . str_replace(' ','_',Auth::user()->name) . "-" . $user->events->aliases . $user->events->year. "." . $validation_3->getClientOriginalExtension();

        $update = [
            'validation_1' => $url.'/ktm-'.$validation_1_name,
            'validation_2' => $url.'/pernyataan-'.$validation_2_name,
            'validation_3' => $url.'/kuitansi-'.$validation_3_name,
            'validation_status' => 'pending'
        ];

        if(Auth::user()->details->events->audience === 'school'){
            $validation_4 = $request->file('validation_4');
            $validation_4_name = $user->identity_code . "-" . str_replace(' ','_',Auth::user()->name) . "-" . $user->events->aliases . $user->events->year. "." . $validation_4->getClientOriginalExtension();

            $validation_5 = $request->file('validation_5');
            $validation_5_name = $user->identity_code . "-" . str_replace(' ','_',Auth::user()->name) . "-" . $user->events->aliases . $user->events->year. "." . $validation_5->getClientOriginalExtension();

            $update = [
                'validation_1' => $url.'/kts-'.$validation_1_name,
                'validation_2' => $url.'/delegasi-'.$validation_2_name,
                'validation_3' => $url.'/kuitansi-'.$validation_3_name,
                'validation_4' => $url.'/foto-'.$validation_4_name,
                'validation_5' => $url.'/integritas-'.$validation_5_name,
                'validation_status' => 'pending'
            ];
        }
        try {
            UserDetail::where('id',Auth::user()->details->id)->update($update);
            if(Auth::user()->details->events->audience === 'school'){
                $validation_1->move($url,'/kts-'.$validation_1_name);
                $validation_2->move($url,'/delegasi-'.$validation_2_name,);
                $validation_3->move($url,'/kuitansi-'.$validation_3_name);
                $validation_4->move($url,'/foto-'.$validation_4_name);
                $validation_5->move($url,'/integritas-'.$validation_5_name);
            }else{
                $validation_1->move($url,'/ktm-'.$validation_1_name);
                $validation_2->move($url,'/pernyataan-'.$validation_2_name,);
                $validation_3->move($url,'/kuitansi-'.$validation_3_name);
            }
        } catch (\Throwable $th) {
            throw $th;
        }

        // $e = UserDetail::where('identity_code',$user->identity_code)->first();
        // Mail::to(Auth::user()->email)->send(new VerificationEmail($e));
        return redirect()->route('dashboard.index')->with(['success'=>'Berhasil Melakukan Validasi']);
        // dd($request);
    }

    public function validateAcc($id){
        try {
            UserDetail::find($id)->update([
                'validation_status' => 'active'
            ]);
            $e = UserDetail::where('id',$id)->first();
            Mail::to($e->users['email'])->send(new VerificationEmail($e));
            return redirect()->back();
        } catch (\Throwable $th) {
            throw $th;
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $data = User::where('users.id',Auth::user()->id)->join('user_details', 'users.id', '=', 'user_details.id_users')->first();
        return view('user.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = User::where('users.id',$id)->join('user_details', 'users.id', '=', 'user_details.id_users')->first();
        echo $data;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/mentor/add.blade.php
@extends('layouts.dash-user')

@section('content')
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">

            </div>
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-12">
                            <h3 class="mb-0">Tambahkan Pendamping </h3>
                        </div>

                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" action="{{route('pendamping.store')}}">
                        @csrf
                            <h6 class="heading-small text-muted mb-4">Informasi Pendamping</h6>
                            <div class="pl-lg-4">
                            {{-- Nama --}}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-name">Nama Pendamping</label>
                                        <input type="text" id="input-name" class="form-control" name="name"
                                        placeholder="Masukkan Nama Pendamping Anda" required>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-initial">NIP</label>
                                        <input type="text" id="input-initial" class="form-control @error('identity_code') is-invalid @enderror" name="identity_code"
                                        placeholder="Masukkan NIP Pendamping Anda" required>
                                        @error('identity_code')
                                            <div class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-initial">No HP Pendamping</label>
                                        <input type="text" id="input-initial" class="form-control" name="phone"
                                        placeholder="Masukkan No HP Pendamping Anda" required>
                                    </div>
                                </div>
                            </div>
{{--
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-name">Instansi</label>
                                        <select name="academy_id" class="form-control " aria-label="Default select example" required>
                                            @foreach ($academy as $items)
                                            <option value="{{ $items->id }}">{{ $items->academy_name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>

                            </div>
                            <hr class="my-4" />
                            <!-- Icons -->
                            <h6 class="heading-small text-muted mb-4">Event</h6>
                            <div class="pl-lg-4">
                                <div class="row">

                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label class="form-control-label" for="input-logo">Photo Profile</label>
                                            <select name="event_id" class="form-control " aria-label="Default select example" required>
                                                @foreach ($event as $items)
                                                <option value="{{ $items->id }}">{{ $items->event_name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div> --}}
                            <button type="submit" class="btn btn-warning w-100">Simpan Data</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/mentor/index.blade.php
@extends('layouts.dash-user')

@section('content')

<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-12 col-12 text-right">
                    <a href="{{route('pendamping.create')}}" class="btn btn-sm btn-neutral">Tambah Pendamping</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div class="card">
                <!-- Card header -->
                <div class="card-header border-0">
                    <h3 class="mb-0">Pendamping </h3>
                </div>

                {{-- success --}}
                @if(session('success'))
                <div class="alert alert-success mb-3 mx-4" role="alert">
                    {{session('success')}}
                </div>
                @endif

                <!-- Light table -->
                <div class="table-responsive">
                    <table class="table align-items-center table-flush" style="height: 200px">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col" class="sort" data-sort="name">Nama Pendamping</th>
                                <th scope="col" class="sort" data-sort="date">NIP</th>
                                <th scope="col" class="sort" data-sort="date">Instansi</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody class="list">
                            @foreach ($data as $item)
                            <tr>
                                <th scope="row">
                                    <div class="media align-items-center">
                                        <div class="media-body">
                                            <span class="name mb-0 text-sm">{{$item->name}} </span>
                                        </div>
                                    </div>
                                </th>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <span class="completion mr-2">{{$item->identity_code}}</span>
                                    </div>
                                </td>
                                <td>
                                  <div class="d-flex align-items-center">
                                      <span class="completion mr-2">{{$item->academy["academy_name"]}}</span>
                                  </div>
                              </td>
                                <td class="text-right">
                                    <div class="dropdown">
                                        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                            <a class="dropdown-item" href="{{ route('pendamping.edit',['pendamping' => $item->id]) }}">Edit Data</a>
                                            <form action="{{route('pendamping.destroy',['pendamping' => $item->id])}}"
                                                method="post">
                                                @csrf
                                                @method('delete')
                                                <button class="dropdown-item">Hapus Data</button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach


                        </tbody>
                    </table>
                </div>
                <!-- Card footer -->
                <div class="card-footer py-4 pagination justify-content-end mb-0">
                    {{ $data->links( "pagination::bootstrap-4") }}
                  </div>
            </div>
        </div>
    </div>


</div>

@endsection