routes/web.php
<?php

use App\Http\Controllers\AcademiesController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ContestantController;
use App\Http\Controllers\Admin\EventsController;
use App\Http\Controllers\Admin\LandingPageSettingController;
use App\Http\Controllers\Admin\MentorController;
use App\Http\Controllers\Admin\SchoolController;
use App\Http\Controllers\Admin\TimeScheduleController;
use App\Http\Controllers\Admin\TechnicalMeetingController;
use App\Http\Controllers\Admin\UniversityController;
use App\Http\Controllers\Admin\UserListController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\DownloadController;
use App\Http\Controllers\EventRegisterController;
use App\Http\Controllers\LandingController;
use App\Http\Controllers\User\ValidationController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ViewMentorController;
use App\Http\Controllers\ViewTimeScheduleController;
use App\Http\Controllers\ViewUserListController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ResetPasswordController;
use PhpParser\Builder\Class_;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
//
*/


Route::get('/', [LandingController::class,'index']);

Route::get('detail-berita/{id}', [LandingController::class,'detail']);

Route::get('lihat-pdf/{id}', [LandingController::class,'viewPDF']);

Route::get('/blog', function () {
    return view('user.setting.edit');
});

Route::resource('pendamping', ViewMentorController::class);

Route::get('/time', [ViewTimeScheduleController::class, 'indexTimeSchedule']);


// Route::get('/time', function () {
//     return view('user.time');
// });

// Route::get('/pendamping', function () {
//     return view('user.pendamping');
// });

Route::get('/detaillomba', function () {
    return view('competition-detail');
});


Route::prefix('/event')->group(function(){

     // AcademyRegister
        Route::get('school',function(){
            return view('register.academy.school');
        })->name('academies.scholl');

        // UniversityRegister
        Route::get('university',function(){
            return view('register.academy.university');
        })->name('academies.university');


    Route::get('/{id}',[EventController::class,'index'])->name('event.detail');
    Route::get('/{id}/form',[EventController::class,'form'])->name('event.form');
    Route::resource('academies',AcademiesController::class);
    route::resource('register',EventRegisterController::class);

});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// User

route::get('/download/{id}',[DownloadController::class,'downloadbooklet'])->name('downloadbooklet');

route::group(['middleware' => ['role:Users','auth'],'prefix' => 'users'],function(){
    route::resource('dashboard',UserController::class);
    route::get('/list-peserta',[ViewUserListController::class,'index'])->name('listpeserta.index');
    route::get('/validation',[ValidationController::class,'index'])->name('user.validation');
    route::post('/validation',[ValidationController::class,'updateValidation'])->name('user.validate');
});

// Admin
route::group(['middleware' => ['role:Administrator'],'prefix' => 'admin',],function(){
    Route::get('/', [DashboardController::class,'index'])->name('admin.dashboard');

    route::get('download/{id}/{validation_no}',[DownloadController::class,'download'])->name('download');


    route::resource('member',AdminController::class);
    route::resource('mentors',MentorController::class);
    route::resource('schedules',TimeScheduleController::class);
    route::resource('events',EventsController::class);
    route::resource('blogs',BlogController::class);
    route::resource('tm',TechnicalMeetingController::class);
    route::resource('school',SchoolController::class);
    route::resource('university',UniversityController::class);

    Route::get('/cetak_pdf/{id}', [EventsController::class,'cetak_pdf'])->name('cetak_pdf');
    Route::get('/lihat_peserta/{id}', [EventsController::class,'lihat_peserta'])->name('lihat_peserta');
    route::get('/userlist/{id}',[UserListController::class,'index'])->name('userlist.index');
    // route::get('/userlist/{id}',[UserListController::class,'index2'])->name('userlist.index2');
    // Contestant
    route::resource('contestants',ContestantController::class);
    Route::get('/reset_password/{id}',[ResetPasswordController::class,'resetpsd'])->name('reset_password.resetpsd');

   // ACC
    Route::get('/acc/{id}',[ValidationController::class,'validateAcc'])->name('validation.acc');

    // Landing Page Setting
    Route::get('/landing',[LandingPageSettingController::class,'getLandingSet'])->name('landing.index');
    Route::post('/post',[LandingPageSettingController::class,'updateLandingSet'])->name('landing.update');

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable,HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'img_url'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function details()
    {
        return $this->hasOne(UserDetail::class,'id_users');
    }
}

app/Http/Controllers/User/ValidationController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Mail\VerificationEmail;
use App\Models\Event;
use App\Models\User;
use App\Models\UserDetail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;

class ValidationController extends Controller
{
    //

    public function index(){

        $path = Storage::disk('local')->get('public/landing_page_config.json');
        $data = json_decode($path,true);

        $url_document = $data['url_document'];

        if(Auth::user()->details->events->audience === "university"){
            return view('user.validation.university');
        }else{
            return view('user.validation.school')->with(compact('url_document'));
        }
    }

    public function updateValidation(Request $request){
        $request->validate([
            'validation_1' => 'image|mimes:jpeg,jpg,png|max:5000',
            'validation_2' => 'image|mimes:jpeg,jpg,png|max:5000',
            'validation_3' => 'image|mimes:jpeg,jpg,png|max:5000',
            'validation_4' => 'image|mimes:jpeg,jpg,png|max:5000',
            'validation_5' => 'image|mimes:jpeg,jpg,png|max:5000'
        ],[
            'validation_1.image' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_2.image' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_3.image' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_4.image' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_5.image' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_1.mimes' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_2.mimes' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_3.mimes' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_4.mimes' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_5.mimes' => "Format file yang di dukung (JPG,jpeg,jpg,png)",
            'validation_1.max' => "Format file maksimal 5 MB",
            'validation_2.max' => "Format file maksimal 5 MB",
            'validation_3.max' => "Format file maksimal 5 MB",
            'validation_4.max' => "Format file maksimal 5 MB",
            'validation_5.max' => "Format file maksimal 5 MB"
        ]);
        $user = Auth::user()->details;

        $event = Auth::user()->details->events;
        $event_name = $event->aliases.$event->year;

        $url = 'img/participant/'.$event_name.'/'. strtolower(str_replace(' ','_',Auth::user()->name));

        $validation_1 = $request->file('validation_1');
        $validation_1_name =  $user->identity_code . "-" . str_replace(' ','_',Auth::user()->name) . "-" . $user->events->aliases . $user->events->year. "." . $validation_1->getClientOriginalExtension();


        $validation_2 = $request->file('validation_2');
        $validation_2_name = $user->identity_code . "-" . str_replace(' ','_',Auth::user()->name) . "-" . $user->events->aliases . $user->events->year. "." . $validation_2->getClientOriginalExtension();

        $validation_3 = $request->file('validation_3');
        $validation_3_name = $user->identity_code . "-" . str_replace(' ','_',Auth::user()->name) . "-" . $user->events->aliases . $user->events->year. "." . $validation_3->getClientOriginalExtension();

        $update = [
            'validation_1' => $url.'/ktm-'.$validation_1_name,
            'validation_2' => $url.'/pernyataan-'.$validation_2_name,
            'validation_3' => $url.'/kuitansi-'.$validation_3_name,
            'validation_status' => 'pending'
        ];

        if(Auth::user()->details->events->audience === 'school'){
            $validation_4 = $request->file('validation_4');
            $validation_4_name = $user->identity_code . "-" . str_replace(' ','_',Auth::user()->name) . "-" . $user->events->aliases . $user->events->year. "." . $validation_4->getClientOriginalExtension();

            $validation_5 = $request->file('validation_5');
            $validation_5_name = $user->identity_code . "-" . str_replace(' ','_',Auth::user()->name) . "-" . $user->events->aliases . $user->events->year. "." . $validation_5->getClientOriginalExtension();

            $update = [
                'validation_1' => $url.'/kts-'.$validation_1_name,
                'validation_2' => $url.'/delegasi-'.$validation_2_name,
                'validation_3' => $url.'/kuitansi-'.$validation_3_name,
                'validation_4' => $url.'/foto-'.$validation_4_name,
                'validation_5' => $url.'/integritas-'.$validation_5_name,
                'validation_status' => 'pending'
            ];
        }
        try {
            UserDetail::where('id',Auth::user()->details->id)->update($update);
            if(Auth::user()->details->events->audience === 'school'){
                $validation_1->move($url,'/kts-'.$validation_1_name);
                $validation_2->move($url,'/delegasi-'.$validation_2_name,);
                $validation_3->move($url,'/kuitansi-'.$validation_3_name);
                $validation_4->move($url,'/foto-'.$validation_4_name);
                $validation_5->move($url,'/integritas-'.$validation_5_name);
            }else{
                $validation_1->move($url,'/ktm-'.$validation_1_name);
                $validation_2->move($url,'/pernyataan-'.$validation_2_name,);
                $validation_3->move($url,'/kuitansi-'.$validation_3_name);
            }
        } catch (\Throwable $th) {
            throw $th;
        }

        // $e = UserDetail::where('identity_code',$user->identity_code)->first();
        // Mail::to(Auth::user()->email)->send(new VerificationEmail($e));
        return redirect()->route('dashboard.index')->with(['success'=>'Berhasil Melakukan Validasi']);
        // dd($request);
    }

    public function validateAcc($id){
        try {
            UserDetail::find($id)->update([
                'validation_status' => 'active'
            ]);
            $e = UserDetail::where('id',$id)->first();
            Mail::to($e->users['email'])->send(new VerificationEmail($e));
            return redirect()->back();
        } catch (\Throwable $th) {
            throw $th;
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $data = User::where('users.id',Auth::user()->id)->join('user_details', 'users.id', '=', 'user_details.id_users')->first();
        return view('user.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = User::where('users.id',$id)->join('user_details', 'users.id', '=', 'user_details.id_users')->first();
        echo $data;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/index.blade.php
@extends('layouts.dash-user')
@section('content')
<div class="header bg-primary pb-7">

</div>
<div class="container-fluid mt--6">
    <div class="header-body">
        <div class="row">
            <div class="col-xl-6 col-md-6">
                <div class="card">
                  <!-- Card body -->
                    <img class="card-img-top img-fluid" style="max-height: 500px;" src="{{asset('img/theme/user-cover.jpg')}}" alt="Card cover">
                    <div class="card-body">
                      <h3 class="card-title" style="font-weight: 700">Halo , {{Auth::user()->name}}</h3>

                      @if (Auth::user()->details->validation_status == 'unactive')
                      <p class="card-text">Segera lengkapi persyaratan untuk menyelesaikan pendaftaranmu!</p>
                        <a href={{route('user.validation')}} class="btn btn-primary">Selesaikan Pendaftaran</a>
                      @endif

                      {{-- success --}}
                      @if(Auth::user()->details->validation_status=='pending')
                      <p class="card-text">Data sedang dalam proses validasi. Harap ditunggu!</p>
                        <div class="alert alert-warning mb-3 " role="alert">
                            Data Sedang Proses Validasi
                        </div>
                      @elseif (Auth::user()->details->validation_status=='active')
                      <p class="card-text">Selamat! datamu berhasil divalidasi, silahkan cek email untuk bergabung kedalam grup peserta Lomba <span style="font-weight: 700">{{ Auth::user()->details->events->event_name }} ({{ Auth::user()->details->events->aliases }}) {{ Auth::user()->details->events->year }}</span></p>
                        @if (Auth::user()->details->events->tm_time != null)
                            @if (Auth::user()->details->events->tm_method == 'zoom')
                                <a href="{{ Auth::user()->details->events->tm_url }}" class="btn btn-primary w-100">Bergabung ke Virtual Meeting </a>
                            @else
                                <a href="{{ Auth::user()->details->events->tm_url }}" class="btn btn-danger w-100">Bergabung ke Tecnical Meeting (Youtube)</a>
                            @endif
                        @else
                            <div class="alert alert-success mb-3 " role="alert">
                                Data Berhasil Divalidasi
                            </div>
                        @endif
                      @endif

                    </div>
                </div>
            </div>
           @if (Auth::user()->details->validation_status === 'active')
           <div class="col-xl-6 col-md-6">

            <div class="card card-stats ">
              <!-- Card body -->
              <a href={{ route('listpeserta.index') }}>
              <div class="card-body p-5">
                <div class="row">
                  <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">Sekolah</h5>
                    <span class="h2 font-weight-bold mb-0">Lihat Peserta Lain</span>
                  </div>
                  <div class="col-auto">
                    <div class="icon icon-shape bg-gradient-orange text-white rounded-circle shadow">
                      <i class="ni ni-badge"></i>
                    </div>
                  </div>
                </div>
              </div>
              </a>
            </div>

            <div class="card card-stats">
              <!-- Card body -->
              <a href={{ route('pendamping.index') }}>
              <div class="card-body p-5">
                <div class="row">
                  <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">Pendamping</h5>
                    <span class="h2 font-weight-bold mb-0"> Lihat Pendampingmu</span>
                  </div>
                  <div class="col-auto">
                    <div class="icon icon-shape bg-gradient-blue text-white rounded-circle shadow">
                      <i class="ni ni-briefcase-24"></i>
                    </div>
                  </div>
                </div>

              </div>
            </a>
            </div>

            <div class="card card-stats">
              <a href="{{ route('downloadbooklet',['id' => Auth::user()->details->events->id ]) }}">
              <!-- Card body -->
              {{-- <a href="{{ route('downloadbooklet',['id' => Auth::user()->details->events->id, 'booklet_url' => 1 ]) }}"> --}}
              <div class="card-body p-5">
                <div class="row">
                  <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">Dokumentasi</h5>
                    <span class="h2 font-weight-bold mb-0"> Dokumen Pendukung</span>
                  </div>
                  <div class="col-auto">
                    <div class="icon icon-shape bg-gradient-green text-white rounded-circle shadow">
                      <i class="ni ni-books"></i>
                    </div>
                  </div>
                </div>
              </div>
            </a>
            </div>

            <div class="card card-stats ">
              <!-- Card body -->
              <a href={{ route('logout') }} class="card-body px-5" onclick="event.preventDefault();
              document.getElementById('logout-form').submit();">
                <div class="row">
                  <div class="col"><h5 class="card-title text-uppercase text-muted mb-0">Keluar Dari WEB  </h5>
                    <span class="h2 font-weight-bold mb-0">Logout</span>
                  </div>
                  <div class="col-auto">
                    <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                      <i class="ni ni-button-power"></i>
                    </div>
                  </div>
                </div>
              </a>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>

            </div>

          </div>
           @endif

        </div>
    </div>
</div>
@endsection

resources/views/user/pendamping.blade.php
@extends('layouts.dash-user')
@section('content')
<div class="header bg-primary pb-7">

</div>
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
          <div class="card">
            <!-- Card header -->
            <div class="card-header border-0">
              <h3 class="mb-0">Lintas Waktu</h3>
            </div>
            <!-- Light table -->
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col" class="sort" data-sort="name">Lintas Waktu</th>
                    <th scope="col" class="sort" data-sort="budget">Tanggal</th>
                    <th scope="col">Deskripsi</th>
                  </tr>
                </thead>
                <tbody class="list">
                @foreach ($data as $item)
                  <tr>
                    <th scope="row">
                      <div class="media align-items-center">
                        <div class="media-body">
                          <span class="name mb-0 text-sm">{{ $item->schedule }}</span>
                        </div>
                      </div>
                    </th>
                    <td class="budget">
                        {{$item->date_start}} - {{$item->date_end}}
                    </td>
                    <td>
                      <span class="badge badge-dot mr-4">
                        <i class="bg-warning"></i>
                        <span class="status">{{$item->desc}}</span>
                      </span>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
            <!-- Card footer -->
            <div class="card-footer py-4 pagination justify-content-end mb-0">
                {{ $data->links( "pagination::bootstrap-4") }}
              </div>
          </div>
        </div>
      </div>
</div>
@endsection

resources/views/user/success.blade.php
@extends('layouts.users')
@section('content')


<div class="mx-5 my-28"><div class="max-w-xl mx-auto text-center">
    <h2 class="text-2xl font-bold sm:text-3xl">
      Pendaftaran <span class="gradient-text">Berhasil</span>
    </h2>
  
    <p class="mx-auto mt-4 text-sm text-gray-500">
      Halo <span class="font-bold">{{$request->name}}</span> , Waktunya masuk ke dalam akunmu selesaikan proses pendaftaran, Selamat Bergabung
    </p>
  
    <a href={{route('login')}} class="inline-block p-0.5 rounded-full bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 mt-10">

        <span class="block px-14 md:px-20 py-2 md:py-3 font-medium text-white bg-gray-900 rounded-full hover:bg-opacity-75">
            Login
        </span>
    </a>
    
  </div></div>
    
@endsection

resources/views/user/time.blade.php
@extends('layouts.dash-user')
@section('content')
<div class="header bg-primary pb-7">

</div>
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
          <div class="card">
            <!-- Card header -->
            <div class="card-header border-0">
              <h3 class="mb-0">Lintas Waktu</h3>
            </div>
            <!-- Light table -->
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col" class="sort" data-sort="name">Lintas Waktu</th>
                    <th scope="col" class="sort" data-sort="budget">Tanggal</th>
                    <th scope="col">Deskripsi</th>
                  </tr>
                </thead>
                <tbody class="list">
                @foreach ($data as $item)
                  <tr>
                    <th scope="row">
                      <div class="media align-items-center">
                        <div class="media-body">
                          <span class="name mb-0 text-sm">{{ $item->schedule }}</span>
                        </div>
                      </div>
                    </th>
                    <td class="budget">
                        {{$item->date_start}}
                    </td>
                    <td>
                      <span class="badge badge-dot mr-4">
                        <span class="status">{{$item->desc}}</span>
                      </span>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
            <!-- Card footer -->
            <div class="card-footer py-4 pagination justify-content-end mb-0">
                {{ $data->links( "pagination::bootstrap-4") }}
              </div>
          </div>
        </div>
      </div>
</div>
@endsection

resources/views/user/userlist.blade.php
@extends('layouts.dash-user')
@section('content')
<div class="header bg-primary pb-7">

</div>
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
          <div class="card">
            <!-- Card header -->
            <div class="card-header border-0">
              <h3 class="mb-0">Lihat Peserta Lain</h3>
            </div>
            <!-- Light table -->
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col" class="sort" data-sort="name">Nama Peserta</th>
                    <th scope="col" class="sort" data-sort="budget">Nomor Induk Peserta</th>
                  </tr>
                </thead>
                <tbody class="list">
                @foreach ($data as $item)
                  <tr>
                    <th scope="row">
                      <div class="media align-items-center">
                        <div class="media-body">
                          <span class="name mb-0 text-sm">{{ $item->users->name }}</span>
                        </div>
                      </div>
                    </th>
                    <td class="budget">
                        {{$item->identity_code}}
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
            <!-- Card footer -->
            <div class="card-footer py-4 pagination justify-content-end mb-0">
                {{ $data->links( "pagination::bootstrap-4") }}
              </div>
          </div>
        </div>
      </div>
</div>
@endsection